export const DSKS = [
  { name: "Kedaar Iyer", year: 2024 },
  { name: "Christopher Dostilio", year: 2024 },
  { name: "Samael Collins", year: 2024 },
  { name: "Rafael Cenzano", year: 2024 },
  { name: "Jetta McPhee", year: 2023 },
  { name: "Jacob Tehranian", year: 2022 },
  { name: "Alexander Fung", year: 2022 },
  { name: "Glenn Edmonds", year: 2024 },
  { name: "Anagha Iyengar", year: 2024 },
  { name: "Daniel Adomilli", year: 2024 },
  { name: "Claire McManus", year: 2024 },
  { name: "Forrest Rusyniak", year: 2024 },
  { name: "Jackson Wong", year: 2024 },
  { name: "Rebecca Nguyen", year: 2024 },
  { name: "Sunny Sen", year: 2024 },
  { name: "Clay Tilton", year: 2024 },
  { name: "Hannah Drew-Moyer", year: 2024 },
  { name: "Kurt English", year: 2024 },
  { name: "Emily Stickles", year: 2024 },
  { name: "Christopher Hartline", year: 2024 },
  { name: "Aaron Kendall (AK)", year: 2024 },
  { name: "Rosie Rickard", year: 2024 },
  { name: "Jillian Cahill", year: 2024 },
  { name: "Joseph Perciacca", year: 2024 },
  { name: "Michael Giehl", year: 2024 },
  { name: "Dave Pazzani", year: 2024 },
  { name: "Kristen Fable", year: 2024 },
  { name: "Jess Sitzer", year: 2024 },
  { name: "Chris Lapointe", year: 2024 },
  { name: "Erica Sherman", year: 2024 },
  { name: "Alyssa J. Pasquale", year: 2024 },
  { name: "Dave Tu", year: 2024 },
  { name: "Beth McCooey", year: 2024 },
  { name: "David Rosenstein", year: 2024 },
  { name: "Darin Smith", year: 2024 },
  { name: "Rich Engle", year: 2024 },
  { name: "Steven W. Joy", year: 2024 },
  { name: "Cynthia M.E. Smith", year: 2024 },
  { name: "Peter F. Caracappa", year: 2024 },
  { name: "Michael J. Corbett", year: 2024 },
  { name: "Daniel Bentz", year: 2024 },
  { name: "Matthew Hausmann", year: 2024 },
  { name: "Peter G. Thies", year: 2024 },
  { name: "Connie Vandenbosch", year: 2024 },
  { name: "Daniel T. VanBey", year: 2024 },
  { name: "Scott Kaplan", year: 2024 },
  { name: "Michael Pajaro", year: 2024 },
  { name: "Bryan Lagos", year: 2024 },
  { name: "Michael E. Haber", year: 2024 },
  { name: "DJ", year: 2024 },
  { name: "Quinten M. King", year: 2024 },
  { name: "Paul J. Lavoie", year: 2024 },
  { name: "Robert Rommel", year: 2024 },
  { name: "Robert Kaminsky", year: 2024 },
  { name: "Daniel J. Mashia", year: 2024 },
  { name: "Christine Wickham", year: 2024 },
  { name: "Robert Philhower", year: 2024 },
  { name: "Matthew Terriblile", year: 2024 },
  { name: "David Panagrosso", year: 2024 },
  { name: "Gary Ide", year: 2024 },
  { name: "David Ginsburg", year: 2024 },
  { name: "Stephen M. Austin", year: 2024 },
  { name: "Richard Tarro", year: 2024 },
  { name: "Gary Flodin", year: 2024 },
  { name: "Diane J. Esemplare", year: 2024 },
  { name: "David R. Kanis", year: 2024 },
  { name: "Andrew Rossbach", year: 2024 },
  { name: "Carl Westerdahl", year: 2024 },
  { name: "Ken Bienstock", year: 2024 },
  { name: "Paul Sicard", year: 2024 },
  { name: "Jeffrey DeBarr", year: 2024 },
  { name: "Larry Mandkelkehr", year: 2024 },
  { name: "Paul Fleming", year: 2024 },
  { name: "Thomas McDermott", year: 2024 },
  { name: "Kathy Goff", year: 2024 },
  { name: "Michael Schneider", year: 2024 },
  { name: "Al Stone", year: 2024 },
  { name: "Steve Coughlan", year: 2024 },
  { name: "Byron Evans", year: 2024 },
  { name: "Tom Goodell", year: 2024 },
  { name: "King Gee", year: 2024 },
  { name: "Bryan Goddard", year: 2024 },
  { name: "Bob Sieffert", year: 2024 },
  { name: "Ted Wasilewski", year: 2024 },
  { name: "Bruce Newhall", year: 2024 },
  { name: "Steven Herman", year: 2024 },
  { name: "George Spagna", year: 2024 },
  { name: "Wayne Ranbom", year: 2024 },
  { name: "Bill Springer", year: 2024 },
  { name: "Lee Leclair", year: 2024 },
  { name: "Tom Lefevre", year: 2024 },
  { name: "Tim Johnson", year: 2024 },
  { name: "Jay Lubin", year: 2024 },
  { name: "Carmen Maietta", year: 2024 },
  { name: "Thomas Kershaw", year: 2024 },
  { name: "Dave Goodrich", year: 2024 },
  { name: "York Freund", year: 2024 },
  { name: "Steven Richel", year: 2024 },
  { name: "John Rasmussen", year: 2024 },
  { name: "Richard Fuhrman", year: 2024 },
];

export const OLAS = [
  { name: "Kedaar Iyer", year: 2024 },
  { name: "Jetta McPhee", year: 2023 },
  { name: "Daegan Fuss", year: 2023 },
  { name: "Cole Belog", year: 2023 },
  { name: "Dylan Weibel", year: 2023 },
  { name: "Samuel Youngs", year: 2022 },
  { name: "Nicholas Gangi", year: 2022 },
  { name: "John G Civetta", year: 2024 },
  { name: "Michael A. Murawski", year: 2024 },
  { name: "Thomas J. McNellis, Jr.", year: 2024 },
  { name: "Stephen M. Austin", year: 2024 },
  { name: "Matthew T. Terribile", year: 2024 },
  { name: "Robert Philhower", year: 2024 },
  { name: "Cynthia Smith", year: 2024 },
  { name: "Steve Joy", year: 2024 },
  { name: "Bernard Derboven", year: 2024 },
  { name: "Ben Walters", year: 2024 },
];
