name: Docker Build Test

on:
  pull_request:
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "**.yml"
      - "**.json"
      - "Dockerfile"
      - ".dockerignore"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Log in to Docker Hub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Docker Image"
        run: |
          docker build -t apoez-frontend .

      - name: "Run Docker Container"
        run: |
          docker run -d --name apoez-frontend-container apoez-frontend
          sleep 30
          docker logs apoez-frontend-container
          docker stop apoez-frontend-container
      
      - name: "Check for Container Exit Code"
        id: check_exit_code
        run: |
          docker inspect apoez-frontend-container --format='{{.State.ExitCode}}'
          docker rm apoez-frontend-container

      - name: "Fail if Container Fails"
        if: steps.check_exit_code.outputs.exit_code != '0'
        run: exit 1