name: TypeScript Check

on:
  pull_request:
    paths:
      - "**.ts"
      - "**.tsx"

permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Typescript check
        run: tsc --noEmit
